akanza/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'task'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task.urls')),
]

task/urls.py
from django.urls import path
from task.views import MainSiteView, RegisterView, logout_view, login_view, PostView, CommentsView, NotificationsView, \
    like_view, subscribe_view


urlpatterns = [
    path('', MainSiteView.as_view(), name='main_site'),
    path('register/', RegisterView.as_view(), name='register'),
    # login/out views
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    # add post form
    path('addpost/', PostView.as_view(), name='addpost'),
    path('comments/', CommentsView.as_view(), name='comments'),
    # activityservice
    path('notifications/', NotificationsView.as_view(), name='notifications'),
    # add like
    path('like/', like_view, name='like'),
    # add subscriptions
    path('subscribe', subscribe_view, name='subscribe'),
]

task/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType


# user subscribtions
class UserModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_subscribe = models.ForeignKey(User, related_name='user_subscribe', on_delete=models.CASCADE)

    def __str__(self):
        return self.user_subscribe.username


class PostModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(blank=False, max_length=256)
    content = models.TextField(blank=False)
    published = models.DateTimeField(auto_now=True)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class CommentModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(blank=False, max_length=1024)
    published = models.DateTimeField(auto_now=True)
    target_post = models.ForeignKey(PostModel, on_delete=models.CASCADE)
    like = models.IntegerField(default=0)

    def __str__(self):
        return self.target_post.title


class LikesModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    #  todo |name Active is not defined| dlaczego?
    #  object = GenericRelation(Active)


class Active(models.Model):
    activity = (
        ('p', 'post'),
        ('l', 'ike'),
        ('c', 'comment'),
        ('s', 'subscribe'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity_type = models.CharField(max_length=1, choices=activity)
    date = models.DateTimeField(auto_now_add=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

task/forms.py
from django import forms
from task.models import PostModel, CommentModel


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=128, required=True, label='username')
    password1 = forms.CharField(widget=forms.PasswordInput, required=True, label='password')
    password2 = forms.CharField(widget=forms.PasswordInput, required=True, label='reapit password')
    email = forms.EmailField(required=True, label='email')


class LoginForm(forms.Form):
    username = forms.CharField(max_length=128, label='username', required=True, widget=forms.TextInput)
    password = forms.CharField(required=True, label='password', widget=forms.PasswordInput)


class PostForm(forms.ModelForm):
    class Meta:
        model = PostModel
        fields = ['title', 'content']

task/views.py
from django.shortcuts import render, redirect
from django.views import View
from task.forms import RegisterForm, LoginForm, PostForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from task.models import PostModel, UserModel, CommentModel, LikesModel, Active
from django.contrib import messages
from task.services import time_count, ActivityService


class MainSiteView(View):
    """
    main site
    """
    def get(self, request):
        posts = PostModel.objects.all().order_by('-published')
        for post in posts:
            post.published = time_count(post.published)

        data = {
            'posts': posts,
        }
        return render(request, 'mainsite.html', data)


class RegisterView(View):
    """
    register new user
    """

    def get(self, request):
        register_form = RegisterForm()
        form = {
            'form': register_form,
        }
        return render(request, 'register.html', form)

    def post(self, request):
        data = RegisterForm(request.POST)
        if data.is_valid():
            username = data.cleaned_data['username']
            password1 = data.cleaned_data['password1']
            password2 = data.cleaned_data['password2']
            email = data.cleaned_data['email']
            if password1 != password2:
                pass
            else:
                User.objects.create_user(username=username, password=password1, email=email)
                user = authenticate(username=username, password=password1)
                login(request, user)

                return redirect('/')


def login_view(request):
    """
    user login
    :param request:
    :return: redirect to main site
    """
    username = request.POST['username']
    password = request.POST['password']
    if authenticate(username=username, password=password):
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/')
    else:
        messages.error(request, 'Incorrect login or password.')
        return redirect('/')


def logout_view(request):
    """
    user logout
    :param request:
    :return: redirect to main site
    """
    logout(request)
    return redirect('/')


class PostView(View):
    """
    View display all posts
    """
    def get(self, request):
        form = PostForm()
        data = {
            'add_post_form': form,
        }
        return render(request, 'add_post.html', data)

    """
    add new posts
    """
    def post(self, request):
        data = PostForm(request.POST)
        if data.is_valid():
            title = data.cleaned_data['title']
            content = data.cleaned_data['content']
            post = PostModel(author=request.user, title=title, content=content)
            post.save()

            active = Active(user=request.user, activity_type='p', content_object=post)
            active.save()
            return redirect('/')


class CommentsView(View):
    """
    View allow add and show comments of posts
    """
    def get(self, request):
        post_id = request.GET['post_id']
        post = PostModel.objects.get(id=post_id)
        post.published = time_count(post.published)
        comments = CommentModel.objects.filter(target_post=post.id)
        for coment in comments:
            coment.published = time_count(coment.published)
        data = {
            'post': post,
            'comments': comments,
        }
        return render(request, 'comment.html', data)

    def post(self, request):
        content = request.POST['content']
        post_id = request.POST['post_id']
        target_post = PostModel.objects.get(id=post_id)
        author = request.user
        comment = CommentModel(author=author, content=content, target_post=target_post)
        comment.save()

        active = Active(user=request.user, activity_type='c', content_object=comment)
        active.save()
        return redirect('/')


class NotificationsView(View):
    """
    when get method, selsect user, then choice activity
    """
    def get(self, request):
        user = request.user
        actives = ActivityService.active(user=user)
        data = {
            'group': actives[0],
            'single': actives[1],
        }
        return render(request, 'notifications.html', data)


def like_view(request):
    """
    get post_id and add like to database
    """
    #  check if user is logged
    # if request.user.is_authenticated:
    #     user = request.user
    #     comment = ''
    #     post = ''
    #
    #     #  check what user liked
    #     if 'comment' in request.GET:
    #         comment = request.GET['comment']
    #         obj = CommentModel.objects.get(id=comment)
    #     else:
    #         post = request.GET['post']
    #         obj = PostModel.objects.get(id=post)
    #
    #     #  check if user liked earlier
    #     if Active.objects.filter(user=user, content_object=obj):
    #         messages.error(request, 'Your already liked this post.')
    #         return redirect('/')
    #     else:
    #         # add like to CommentModel or LikeModel
    #         if comment != '':
    #             comment = CommentModel.objects.get(id=comment)
    #             comment.like += 1
    #             comment.save()
    #         else:
    #             post = PostModel.objects.ge(id=post)
    #             post.like += 1
    #             post.save()
    #
    #         active = Active(user=request.user, activity_type='l', content_object=obj)
    #         active.save()
    #     return redirect('/')
    # else:
    #     messages.error(request, 'You have to be logged..')
    #     return redirect('/')


def subscribe_view(request):
    """
    add subscriptions
    """
    user = request.user
    author_id = request.POST['author_id']
    target_user = User.objects.get(id=author_id)
    #  check if user subscribe user earlier
    if UserModel.objects.filter(user=user, user_subscribe=target_user):
        messages.error('You already subscribe this user.')
        return redirect('/')
    #  check if user try subscribe himself
    elif UserModel.objects.filter(user=user, user_subscribe=user):
        messages.error('You cant subscribe your self.')
        return redirect('/')
    else:
        user_model = UserModel(user=user, user_subscribe=target_user)
        user_model.save()

        active = Active(user=user, activity_type='s', content_object=user_model)
        active.save()
        return redirect('/')

task/templates/add_post.html
{% block content %}
<div>
    <form action="{% url 'addpost' %}" method="POST">
        {% csrf_token %}
        {{ add_post_form.as_p }}
        <input type="submit" value="Add post">
    </form>
</div>

{% endblock %}

task/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task</title>
</head>
<body>
<a href="{% url 'main_site' %}"><h1>Task</h1></a>
<div>
    {% if logged %}
        <h3>Hello {{ username }}</h3>
        <button><a href="{% url 'logout' %}">Logout</a></button>
        <button><a href="{% url 'addpost' %}">Add post</a></button>
        <button><a href="{% url 'notifications' %}">Notifications</a></button>

    {% else %}
    <p>You have to be logged, if you want add posts and use Activity Service</p>
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        {{ login_form.as_p }}
        <label><input type="submit" value="login"></label>
    </form>
    <button><a href="{% url 'register' %}">Register</a></button>
    {% endif %}
</div>
{% block content %}{% endblock %}
</body>
</html>

task/templates/comment.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div style="border: solid black 2px;">
        <h4>Title: {{ post.title }}</h4>
        <p>{{ post.content }}</p>
        <span>{{ post.author }}</span> | Like: {{ post.like }} |
        <span>{{ post.published.0 }} {{ post.published.1 }} ago</span>
    </div>
    <button>Like</button>
    <div>
        <h3>Add comment</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <p><label><textarea name="content" placeholder="comment"></textarea></label></p>
            <input name="post_id" type="number" value="{{ post.id }}" hidden>
            <p><label><input type="submit" value="comment"></label></p>
        </form>
    </div>
    {% if messages %}
       {% for message in messages %}
           <p style="color: red;">{{ message }}</p>
       {% endfor %}
    {% endif %}
    {% for comment in comments %}
        <div style="border: solid black 2px;">
            <p>{{ comment.content }}</p>
            <p>{{ comment.author }} | like: {{ comment.like }} | published: {{ comment.published.0 }}
                {{ comment.published.1 }} ago</p>
        </div>
        <form action="{% url 'like' %}" method="GET">
            {% csrf_token %}
            <input type="number" name="comment" value="{{ comment.id }}" hidden>
            <input type="submit" value="Like">
        </form>
    {% endfor %}
</div>

{% endblock %}

task/templates/mainsite.html
{% extends 'base.html' %}
{% block content %}
<div style="background-color: #222;">
    <h3 style="color: white; text-align: center; margin: 10px; padding: 10px;">Posts</h3>
</div>
<div>
    {% if messages %}
       {% for message in messages %}
           <p style="color: red;">{{ message }}</p>
       {% endfor %}
    {% endif %}
    {% for i in posts %}
        <div style="border: solid black 2px;">
            <h4>Title: {{ i.title }}</h4>
            <p>{{ i.content }}</p>
            <span>{{ i.author }}</span> | Like: {{ i.like }} |

            <span>{{ i.published.0 }} {{ i.published.1 }} {{ i.published.2 }} ago</span>
        </div>

        <form action="{% url 'like' %}" method="GET">
            {% csrf_token %}
            <input type="number" name="post" value="{{ i.id }}" hidden>
            <input type="submit" value="Like">
        </form>

        <form action="{% url 'comments' %}" method="GET">
            {% csrf_token %}
            <input name="post_id" value="{{ i.id }}" type="number" hidden>
            <input type="submit" value="Comments">
        </form>

        <form action="{% url 'subscribe' %}" method="POST">
            {% csrf_token %}
            <input name="author_id" value="{{ i.author.id }}" type="number" hidden>
            <input type="submit" value="Subscribe">
        </form>

    {% endfor %}
</div>
{% endblock %}

task/templates/notifications.html
<a href="{% url 'main_site' %}"><h1>task</h1></a>
{% block content %}
<h1>Activity Service</h1>
<h2>{{ user }}</h2>
{% if get_method %}
    <div>
        <form action="{% url 'activityservice' %}" method="POST">
            {% csrf_token %}
            <input list="users" name="user">
                <datalist id="users">
                    {% for i in users %}
                        <option value="{{ i }}">
                    {% endfor %}
                </datalist>
            <input type="submit">
        </form>
    </div>
{% else %}

<div>
    {% if group %}
    <p>{{ group.0.user }} {{ group.0.get_activity_type_display }}

        {% for active in group %}
            {{ active.content_object }},
        {% endfor %}

        {{ group.0.date.0 }}
     {{ group.0.date.1 }} ago.</p>
    <p>-------------------------------------------------------------------------------------------------</p>

    {% endif %}
</div>

{% if single %}
{% for i in single %}
<p>{{ i.user }} {{ i.get_activity_type_display }}

    {% if i.content_object.title %}
        {{ i.content_object.title }},
    {% elif i.content_object.target_post %}
        {{ i.content_object.target_post }},
    {% elif i.content_object.user_subscribe %}
        {{ i.content_object.user_subscribe }}
    {% endif %}

    {{ i.date.0 }} {{ i.date.1 }} ago.</p>
<p>-------------------------------------------------------------------------------------------------</p>
{% endfor %}
{% endif %}

{% endif %}
{% endblock %}

task/templates/register.html
{% block content %}
<h1>Register account</h1>
<div>
    <form action="{% url 'register' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
    </form>
</div>
{% endblock %}

task/templates/test.html
{% extends 'base.html' %}
{% block content %}
TESTS
{{ author }}
{% endblock %}